# 微服务架构部署配置
# 适用于企业级用户，支持前后端分离和独立数据库

version: '3.8'

services:
  # 前端服务 - Vue应用 + Nginx
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: stock-scanner-frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=http://backend:8888
      - VITE_APP_TITLE=Stock Scanner
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - stock-scanner-network

  # 后端服务 - Python FastAPI
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: stock-scanner-backend
    ports:
      - "8888:8888"
    environment:
      - API_KEY=${API_KEY:-}
      - API_URL=${API_URL:-}
      - API_MODEL=${API_MODEL:-}
      - API_TIMEOUT=${API_TIMEOUT:-30}
      - ANNOUNCEMENT_TEXT=${ANNOUNCEMENT_TEXT:-}
      - ENABLE_USER_SYSTEM=true
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-secret-key-change-in-production}
      - DATABASE_URL=postgresql://stock_user:stock_password@postgres:5432/stock_scanner
      - POSTGRES_USER=stock_user
      - POSTGRES_PASSWORD=stock_password
      - POSTGRES_DB=stock_scanner
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/api/config"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - stock-scanner-network

  # PostgreSQL数据库
  postgres:
    image: postgres:15-alpine
    container_name: stock-scanner-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=stock_scanner
      - POSTGRES_USER=stock_user
      - POSTGRES_PASSWORD=stock_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stock_user -d stock_scanner"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - stock-scanner-network

  # 反向代理 - 统一入口
  nginx:
    image: nginx:stable-alpine
    container_name: stock-scanner-nginx
    ports:
      - "80:80"
      # - "443:443"  # 启用SSL时取消注释
    volumes:
      - ./nginx/nginx.microservices.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
      # - ./nginx/ssl:/etc/nginx/ssl  # 启用SSL时取消注释
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - stock-scanner-network

networks:
  stock-scanner-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local 